### ISSUE TITLE
Certain PDFs return errors requiring poppler-utils to be installed in base image

### ISSUE THREAD

**Issue by myrison** [plamola/ocr-joplin-notes#7]
When processing certain PDFs, I encounter the following error.  I've forked the repo and added these dependencies as well as the separate fixes from @harun27 (which fixes the errors below). 

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/cli.py", line 89, in <module>
    sys.exit(main())  # pragma: no cover
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/cli.py", line 79, in main
    res = run_mode(mode, tag)
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/ocr_joplin_notes.py", line 79, in run_mode
    return full_run(tag)
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/ocr_joplin_notes.py", line 91, in full_run
    return perform_on_tagged_notes(perform_ocr_for_note, tag_id)
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/joplin_api.py", line 75, in perform_on_tagged_notes
    usage_function(note.get("id"))
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/ocr_joplin_notes.py", line 146, in perform_ocr_for_note
    result_tag = ocr_resources(note)
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/ocr_joplin_notes.py", line 160, in ocr_resources
    data = ocr_resource(resource, ADD_PREVIEWS and note.markup_language == 2)
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/ocr_joplin_notes.py", line 225, in ocr_resource
    ocr_result = extract_text_from_pdf(full_path, language=LANGUAGE)
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/file_ocr.py", line 80, in extract_text_from_pdf
    extracted_image = pdf_page_as_image(filename, i)
  File "/usr/local/lib/python3.9/site-packages/ocr_joplin_notes/file_ocr.py", line 30, in pdf_page_as_image
    pages = convert_from_path(filename, dpi=600, grayscale=True)
  File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 98, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 484, in pdfinfo_from_path
    raise PDFInfoNotInstalledError(
pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
Starting OCR for tag ojn_yes.
```

The key error above is this one:

**raise PDFInfoNotInstalledError(
pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?**

This is fixed by installing the poppler-utils in the Dockerfile.

**Comment by plamola** [comment]
Thanks for reporting this. It has been fixed in the latest release, 0.3.3
